const notesItems = [
  {
    id: 1,
    name: "Make new app",
    created: "2023-07-26",
    content: "Make new app till 30 days",
    category: "Idea",
    dates: [],
    archived: false,
  },
  {
    id: 2,
    name: "Shopping list",
    created: "2023-07-25",
    content: "Buy tomato, potato and cheese",
    category: "Task",
    dates: [],
    archived: false,
  },
  {
    id: 3,
    name: "Watch movie",
    created: "2023-07-24",
    content: "Watch movie 10/10/2023",
    category: "Random Thought",
    dates: ["10/10/2022"],
    archived: false,
  },
  {
    id: 4,
    name: "New feature",
    created: "2023-07-23",
    content: "Make a new feature for app",
    category: "Idea",
    dates: [],
    archived: false,
  },
  {
    id: 5,
    name: "Do task 2",
    created: "2023-07-30",
    content: "Starn do task 2 and end till 2/8/2023",
    category: "Task",
    dates: ["2/8/2023"],
    archived: false,
  },
  {
    id: 6,
    name: "Clean room",
    created: "2023-07-21",
    content: "Clean my roon",
    category: "Idea",
    dates: [],
    archived: false,
  },
  {
    id: 7,
    name: "Note 7",
    created: "2023-07-20",
    content: "This is a random thought with a date 6/6/2022",
    category: "Random Thought",
    dates: ["6/6/2022"],
    archived: true,
  },
];
export default notesItems;
